'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Reflection
Namespace Create_a_Report_Bound_to_XPObjectSource.nwind

	Partial Public Class Categories
		Inherits XPLiteObject

		Private fCategoryID As Integer
		<Key(True)>
		Public Property CategoryID() As Integer
			Get
				Return fCategoryID
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)(NameOf(CategoryID), fCategoryID, value)
			End Set
		End Property
		Private fCategoryName As String
		<Indexed(Name := "CategoryName", Unique := True), Size(15)>
		Public Property CategoryName() As String
			Get
				Return fCategoryName
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)(NameOf(CategoryName), fCategoryName, value)
			End Set
		End Property
		Private fDescription As String
		<Size(SizeAttribute.Unlimited)>
		Public Property Description() As String
			Get
				Return fDescription
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)(NameOf(Description), fDescription, value)
			End Set
		End Property
		Private fIcon17() As Byte
		<Size(SizeAttribute.Unlimited), MemberDesignTimeVisibility(True)>
		Public Property Icon17() As Byte()
			Get
				Return fIcon17
			End Get
			Set(ByVal value As Byte())
				SetPropertyValue(Of Byte())(NameOf(Icon17), fIcon17, value)
			End Set
		End Property
		Private fIcon25() As Byte
		<Size(SizeAttribute.Unlimited), MemberDesignTimeVisibility(True)>
		Public Property Icon25() As Byte()
			Get
				Return fIcon25
			End Get
			Set(ByVal value As Byte())
				SetPropertyValue(Of Byte())(NameOf(Icon25), fIcon25, value)
			End Set
		End Property
		Private fPicture() As Byte
		<Size(SizeAttribute.Unlimited), MemberDesignTimeVisibility(True)>
		Public Property Picture() As Byte()
			Get
				Return fPicture
			End Get
			Set(ByVal value As Byte())
				SetPropertyValue(Of Byte())(NameOf(Picture), fPicture, value)
			End Set
		End Property
		<Association("ProductsReferencesCategories")>
		Public ReadOnly Property ProductsCollection() As XPCollection(Of Products)
			Get
				Return GetCollection(Of Products)(NameOf(ProductsCollection))
			End Get
		End Property
	End Class

End Namespace
