'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Reflection

Namespace Create_a_Report_Bound_to_XPObjectSource.nwind

    Public Partial Class Categories
        Inherits XPLiteObject

        Private fCategoryID As Integer

        <Key(True)>
        Public Property CategoryID As Integer
            Get
                Return Me.fCategoryID
            End Get

            Set(ByVal value As Integer)
                Call SetPropertyValue(Of Integer)(NameOf(Create_a_Report_Bound_to_XPObjectSource.nwind.Categories.CategoryID), Me.fCategoryID, value)
            End Set
        End Property

        Private fCategoryName As String

        <Indexed(Name:="CategoryName", Unique:=True)>
        <Size(15)>
        Public Property CategoryName As String
            Get
                Return Me.fCategoryName
            End Get

            Set(ByVal value As String)
                Call SetPropertyValue(Of String)(NameOf(Create_a_Report_Bound_to_XPObjectSource.nwind.Categories.CategoryName), Me.fCategoryName, value)
            End Set
        End Property

        Private fDescription As String

        <Size(SizeAttribute.Unlimited)>
        Public Property Description As String
            Get
                Return Me.fDescription
            End Get

            Set(ByVal value As String)
                Call SetPropertyValue(Of String)(NameOf(Create_a_Report_Bound_to_XPObjectSource.nwind.Categories.Description), Me.fDescription, value)
            End Set
        End Property

        Private fIcon_17 As Byte()

        <Size(SizeAttribute.Unlimited)>
        <MemberDesignTimeVisibility(True)>
        Public Property Icon_17 As Byte()
            Get
                Return Me.fIcon_17
            End Get

            Set(ByVal value As Byte())
                Call SetPropertyValue(Of Byte())(NameOf(Create_a_Report_Bound_to_XPObjectSource.nwind.Categories.Icon_17), Me.fIcon_17, value)
            End Set
        End Property

        Private fIcon_25 As Byte()

        <Size(SizeAttribute.Unlimited)>
        <MemberDesignTimeVisibility(True)>
        Public Property Icon_25 As Byte()
            Get
                Return Me.fIcon_25
            End Get

            Set(ByVal value As Byte())
                Call SetPropertyValue(Of Byte())(NameOf(Create_a_Report_Bound_to_XPObjectSource.nwind.Categories.Icon_25), Me.fIcon_25, value)
            End Set
        End Property

        Private fPicture As Byte()

        <Size(SizeAttribute.Unlimited)>
        <MemberDesignTimeVisibility(True)>
        Public Property Picture As Byte()
            Get
                Return Me.fPicture
            End Get

            Set(ByVal value As Byte())
                Call SetPropertyValue(Of Byte())(NameOf(Create_a_Report_Bound_to_XPObjectSource.nwind.Categories.Picture), Me.fPicture, value)
            End Set
        End Property

        <Association("ProductsReferencesCategories")>
        Public ReadOnly Property ProductsCollection As XPCollection(Of Create_a_Report_Bound_to_XPObjectSource.nwind.Products)
            Get
                Return GetCollection(Of Create_a_Report_Bound_to_XPObjectSource.nwind.Products)(NameOf(Create_a_Report_Bound_to_XPObjectSource.nwind.Categories.ProductsCollection))
            End Get
        End Property
    End Class
End Namespace
